### ISSUE TITLE
Not able to dispose LoadToast.

### ISSUE THREAD

**Issue by ShettyGaneshprasad** [fayaz07/load_toast#4]
onPressed: () {
              if (_formKey.currentState.validate()) {
                debugPrint('All validations passed!!!');

                Navigator.pop(context);
                showLoadToast(
                  backgroundColor: Colors.white,
                  indicatorColor: Colors.blue,
                  text: 'Adding Job',
                );
                try {
                  final userdata = Provider.of<User>(context, listen: false);
                  DatabaseService db = DatabaseService(user: userdata);
                  db.updateJobData(companyName, position, salary,
                      jobDescription, jobRequirement);
                } on Exception catch (_) {
                  hideLoadToastWithError();
                }
                hideLoadToastWithSuccess();
              } else {
                showLoadToast(
                  backgroundColor: Colors.white,
                  indicatorColor: Colors.blue,
                  text: 'Please wait...',
                );
                hideLoadToastWithError();
              }
            },

ConsoleError:LoadToast error: LoadToast not shown/disposed

then load toast stuck there in loading state without closing.

**Comment by fayaz07** [comment]
Hi @ShettyGaneshprasad , can you try this
```dart
   onPressed: () {
              if (_formKey.currentState.validate()) {
                debugPrint('All validations passed!!!');

                Navigator.pop(context);
                showLoadToast(
                  backgroundColor: Colors.white,
                  indicatorColor: Colors.blue,
                  text: 'Adding Job',
                );
                try {
                  final userdata = Provider.of<User>(context, listen: false);
                  DatabaseService db = DatabaseService(user: userdata);
                  db.updateJobData(companyName, position, salary,
                      jobDescription, jobRequirement);
                } on Exception catch (_) {
                  hideLoadToastWithError();
                }
                hideLoadToastWithSuccess();
              } else {
                await showLoadToast(
                  backgroundColor: Colors.white,
                  indicatorColor: Colors.blue,
                  text: 'Please wait...',
                );
                hideLoadToastWithError();
              }
            },

```

**Comment by ShettyGaneshprasad** [comment]
Tried that but the same issue (not able to see closing success ):- 
![image](https://user-images.githubusercontent.com/50592455/102874300-4895da80-4468-11eb-8aa7-e1739c7ce54b.png)

check this implementation once

```
 FloatingActionButton(
            onPressed: () async {
              if (_formKey.currentState.validate()) {
                debugPrint('All validations passed!!!');

                Navigator.pop(context);
                showLoadToast(
                  backgroundColor: Colors.white,
                  indicatorColor: Colors.blue,
                  text: 'Adding Job',
                );
                try {
                  final userdata = Provider.of<User>(context, listen: false);
                  DatabaseService db = DatabaseService(user: userdata);
                  db.updateJobData(companyName, position, salary,
                      jobDescription, jobRequirement);
                } on Exception catch (_) {
                  debugPrint('error');
                  hideLoadToastWithError();
                  // hideOverlay();
                }
                debugPrint('sucess');
                hideLoadToastWithSuccess();
                // hideOverlay();
              } else {
                await showLoadToast(
                  backgroundColor: Colors.white,
                  indicatorColor: Colors.blue,
                  text: 'Please wait...',
                );
                hideLoadToastWithError();
              }
            },
          ),
```

**Comment by ShettyGaneshprasad** [comment]
@fayaz07 actually I am starting loading in BottomSheet when we press that button to start the load button we go back to the main screen.
then it should have success loading toast.

**Comment by fayaz07** [comment]
Hi @ShettyGaneshprasad 
you're unable to see the success dialog because all the operations you are doing there are not asynchronous and if you want the exact behavior you are looking for, then you should `await` before every operation such as `showLoadToast`, `hideLoadToast`

**Comment by fayaz07** [comment]
I am closing this issue for now, feel free to re open if you're still facing issues
